language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t otecioann/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true otecioann/react-test npm test

after_success:
    - docker build -t otecioann/multi-client ./client
    - docker build -t otecioann/multi-nginx ./nginx
    - docker build -t otecioann/multi-server ./server
    - docker build -t otecioann/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push otecioann/multi-client
    - docker push otecioann/multi-nginx
    - docker push otecioann/multi-server
    - docker push otecioann/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-211374936125
    bucket_path: docker_multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

